### ISSUE TITLE
Unable to export after manually removing vertex color layers

### ISSUE THREAD

**Issue by progwolff** [Yethiel/re-volt-addon#16]
If I manually remove a vertex color layer, it happens from time to time that I cannot export .w or .ncp files anymore.

When this happens, the `layer` parameter in `layers.py:get_average_vcol2(faces, layer)` is `None`.

I fixed this locally by adding 
```
if not layer:
    return (0,0,0)
```

There might be a cleaner solution.

**Comment by Yethiel** [comment]
Thanks for the report, I'll look into it!

**Comment by Yethiel** [comment]
The issue should be resolved with the [latest version](https://github.com/Yethiel/re-volt-addon/releases/tag/rva_17.1112).

`get_average_vcol2` is used for exporting environment colors. Since the colors are per-face in Re-Volt (not per-vertex), the average color has to be written to the envlist.  
It tried to export the colors even if the `Env` layer didn't exist. Now it gets automatically created if it doesn't.

Feel free to reopen the issue if the problem persists.
